"""Fetch declared sources into the immutable raw layer.

Contract:
  * Every source is pinned to a commit. Nothing floats.
  * Fetched bytes are written once and never modified. If a file already exists
    and its digest matches the lock, we do not re-download it.
  * If a file exists with a *different* digest than the lock, that is an error,
    not something to paper over — upstream changed under a pin, or our disk lied.
  * `--relock` recomputes digests and rewrites sources.lock.json. It is the only
    operation permitted to change a recorded digest, and it is never automatic.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tomllib
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES_TOML = ROOT / "sources.toml"
LOCK_PATH = ROOT / "sources.lock.json"
RAW_DIR = ROOT / "data" / "raw"

USER_AGENT = "quranlab/0.1 (+research pipeline; contact via repository)"


class FetchError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_declarations() -> list[dict]:
    with SOURCES_TOML.open("rb") as fh:
        return tomllib.load(fh)["source"]


def raw_url(src: dict, path: str) -> str:
    if src["kind"] != "github-raw":
        raise FetchError(f"unsupported source kind: {src['kind']!r}")
    return f"https://raw.githubusercontent.com/{src['repo']}/{src['commit']}/{path}"


def local_path(src: dict, path: str) -> Path:
    return RAW_DIR / src["id"] / path


def _download(url: str, dest: Path) -> None:
    """Fetch a URL to dest. urllib first; curl as a fallback for proxy setups
    where the CA bundle is wired into curl but not into Python's ssl defaults."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(req, timeout=120) as resp, tmp.open("wb") as out:
            shutil.copyfileobj(resp, out)
    except Exception as exc:  # noqa: BLE001 — any transport failure is worth retrying via curl
        if not shutil.which("curl"):
            raise FetchError(f"{url}: {exc}") from exc
        result = subprocess.run(
            ["curl", "-sS", "--fail", "--location", "--max-time", "180",
             "-A", USER_AGENT, "-o", str(tmp), url],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            tmp.unlink(missing_ok=True)
            raise FetchError(f"{url}: {result.stderr.strip() or exc}") from exc
    os.replace(tmp, dest)


def fetch_all(relock: bool = False, force: bool = False) -> dict:
    declarations = load_declarations()
    previous = json.loads(LOCK_PATH.read_text()) if LOCK_PATH.exists() else {"files": {}}
    prev_files = previous.get("files", {})

    lock_files: dict[str, dict] = {}
    problems: list[str] = []

    for src in declarations:
        for rel in src["files"]:
            key = f"{src['id']}/{rel}"
            dest = local_path(src, rel)
            url = raw_url(src, rel)
            expected = prev_files.get(key, {}).get("sha256")

            if force and dest.exists():
                dest.unlink()

            if dest.exists() and expected and sha256_file(dest) == expected:
                digest = expected
            else:
                if not dest.exists():
                    print(f"  fetch  {key}", file=sys.stderr)
                    _download(url, dest)
                digest = sha256_file(dest)
                if expected and digest != expected and not relock:
                    problems.append(
                        f"{key}: digest mismatch\n"
                        f"    locked  {expected}\n"
                        f"    on disk {digest}\n"
                        f"    Upstream moved under a pinned commit, or the file was edited. "
                        f"Investigate before running `fetch --relock`."
                    )

            lock_files[key] = {
                "source": src["id"],
                "repo": src["repo"],
                "commit": src["commit"],
                "path": rel,
                "url": url,
                "sha256": digest,
                "bytes": dest.stat().st_size,
                "license": src.get("license", "unspecified"),
            }

    if problems:
        raise FetchError("integrity check failed:\n" + "\n".join(problems))

    lock = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "note": "Generated by `python -m quranlab fetch --relock`. Do not hand-edit.",
        "files": dict(sorted(lock_files.items())),
    }
    if relock or not LOCK_PATH.exists():
        # Keep the timestamp stable when nothing else changed, so the lock file
        # does not churn in git on every re-run.
        if LOCK_PATH.exists():
            old = json.loads(LOCK_PATH.read_text())
            if old.get("files") == lock["files"]:
                lock["generated_at"] = old.get("generated_at", lock["generated_at"])
        LOCK_PATH.write_text(json.dumps(lock, indent=2, ensure_ascii=False) + "\n")
        print(f"  wrote  {LOCK_PATH.relative_to(ROOT)}", file=sys.stderr)

    return lock


def read_source(source_id: str, rel: str) -> bytes:
    """Read a raw file, verifying it against the lock before handing it over.

    Every ingest path goes through here. Nothing reads data/raw/ directly.
    """
    lock = json.loads(LOCK_PATH.read_text())
    key = f"{source_id}/{rel}"
    entry = lock["files"].get(key)
    if entry is None:
        raise FetchError(f"{key} is not in sources.lock.json; run `quranlab fetch`")
    path = RAW_DIR / source_id / rel
    if not path.exists():
        raise FetchError(f"{key} not fetched; run `quranlab fetch`")
    digest = sha256_file(path)
    if digest != entry["sha256"]:
        raise FetchError(
            f"{key}: sha256 {digest} does not match locked {entry['sha256']}"
        )
    return path.read_bytes()


def read_json(source_id: str, rel: str):
    return json.loads(read_source(source_id, rel))
